import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { runInitCommand } from "../src/cli/commands/init.js";

const createdDirectories: string[] = [];

async function createTempRepository(): Promise<string> {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "next-codex-workflow-generate-"));
  createdDirectories.push(tempRoot);
  return tempRoot;
}

async function createSupportedRepository(rootDir: string): Promise<void> {
  await writeFile(
    path.join(rootDir, "package.json"),
    JSON.stringify(
      {
        name: "fixture-app-router",
        dependencies: {
          next: "^16.0.0",
          react: "^19.0.0"
        },
        devDependencies: {
          typescript: "^5.9.0"
        },
        scripts: {
          dev: "next dev",
          build: "next build",
          lint: "eslint .",
          typecheck: "tsc --noEmit"
        }
      },
      null,
      2
    )
  );
  await writeFile(path.join(rootDir, "package-lock.json"), "");
  await writeFile(path.join(rootDir, "tsconfig.json"), "{}");
  await mkdir(path.join(rootDir, "app"), { recursive: true });
  await writeFile(path.join(rootDir, "app", "page.tsx"), "export default function Page() { return null; }");
  await mkdir(path.join(rootDir, "app", "dashboard"), { recursive: true });
  await writeFile(
    path.join(rootDir, "app", "dashboard", "page.tsx"),
    "export default function Dashboard() { return null; }"
  );
}

afterEach(async () => {
  await Promise.all(createdDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe("workflow file generation", () => {
  it("writes the core managed files for a supported repository", async () => {
    const rootDir = await createTempRepository();
    await createSupportedRepository(rootDir);

    const result = await runInitCommand(
      {
        yes: false,
        performance: false,
        routes: [],
        externalSkillSet: "recommended",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: rootDir }
    );

    expect(result.exitCode).toBe(0);

    const agentsMd = await readFile(path.join(rootDir, "AGENTS.md"), "utf8");
    const codexConfig = await readFile(path.join(rootDir, ".codex", "config.toml"), "utf8");
    const verifyScript = await readFile(path.join(rootDir, "scripts", "verify-agent-workflow.mjs"), "utf8");
    const planArtifact = await readFile(path.join(rootDir, "agent-workflow", "artifacts", "PLAN.md"), "utf8");
    const managedRegistry = await readFile(
      path.join(rootDir, "agent-workflow", "manifest", "managed-files.json"),
      "utf8"
    );
    const skillsLock = await readFile(
      path.join(rootDir, "agent-workflow", "manifest", "skills-lock.json"),
      "utf8"
    );
    const skillFile = await readFile(
      path.join(rootDir, ".agents", "skills", "task-clarification", "SKILL.md"),
      "utf8"
    );
    const externalSkillFile = await readFile(
      path.join(rootDir, ".agents", "skills", "next-best-practices", "SKILL.md"),
      "utf8"
    );
    const externalSkillReference = await readFile(
      path.join(rootDir, ".agents", "skills", "next-best-practices", "file-conventions.md"),
      "utf8"
    );
    const reactRule = await readFile(
      path.join(rootDir, ".agents", "skills", "vercel-react-best-practices", "rules", "async-parallel.md"),
      "utf8"
    );
    const componentReference = await readFile(
      path.join(rootDir, ".agents", "skills", "building-components", "references", "principles.mdx"),
      "utf8"
    );
    const designGuidelineReference = await readFile(
      path.join(
        rootDir,
        ".agents",
        "skills",
        "web-design-guidelines",
        "references",
        "web-interface-guidelines.md"
      ),
      "utf8"
    );

    expect(agentsMd).toContain("Generated by next-codex-workflow-kit");
    expect(agentsMd).toContain("# Feature Work Routing Rules");
    expect(codexConfig).toContain("[agents.verifier]");
    expect(verifyScript).toContain("CHECK_ORDER");
    expect(planArtifact).toContain("# Task Summary");
    expect(managedRegistry).toContain("\"paths\"");
    expect(skillsLock).toContain("\"next-best-practices\"");
    expect(skillFile).toContain("name: task-clarification");
    expect(externalSkillFile).toContain("name: next-best-practices");
    expect(externalSkillReference).toContain("## Project Structure");
    expect(reactRule).toContain("Promise.all()");
    expect(componentReference).toContain("## Composability and Reusability");
    expect(designGuidelineReference).toContain("### Accessibility");
  });

  it("does not write files during dry run", async () => {
    const rootDir = await createTempRepository();
    await createSupportedRepository(rootDir);

    const result = await runInitCommand(
      {
        yes: false,
        performance: false,
        routes: [],
        externalSkillSet: "recommended",
        overwriteManaged: false,
        dryRun: true,
        help: false
      },
      { cwd: rootDir }
    );

    expect(result.exitCode).toBe(0);
    await expect(readFile(path.join(rootDir, "AGENTS.md"), "utf8")).rejects.toThrow();
    expect(result.actions.some((action) => action.endsWith("AGENTS.md"))).toBe(true);
  });

  it("fails with exit code 3 when an unmanaged target file already exists", async () => {
    const rootDir = await createTempRepository();
    await createSupportedRepository(rootDir);
    await writeFile(path.join(rootDir, "AGENTS.md"), "# User-owned file\n");

    const result = await runInitCommand(
      {
        yes: false,
        performance: false,
        routes: [],
        externalSkillSet: "recommended",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: rootDir }
    );

    expect(result.exitCode).toBe(3);
    expect(result.error).toContain("AGENTS.md");
  });

  it("is idempotent when init runs twice with the same options", async () => {
    const rootDir = await createTempRepository();
    await createSupportedRepository(rootDir);

    const firstRun = await runInitCommand(
      {
        yes: false,
        performance: false,
        routes: [],
        externalSkillSet: "recommended",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: rootDir }
    );

    expect(firstRun.exitCode).toBe(0);

    const firstAgentsMd = await readFile(path.join(rootDir, "AGENTS.md"), "utf8");

    const secondRun = await runInitCommand(
      {
        yes: false,
        performance: false,
        routes: [],
        externalSkillSet: "recommended",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: rootDir }
    );

    const secondAgentsMd = await readFile(path.join(rootDir, "AGENTS.md"), "utf8");

    expect(secondRun.exitCode).toBe(0);
    expect(secondAgentsMd).toBe(firstAgentsMd);
  });

  it("adds performance files only when performance mode is enabled", async () => {
    const rootDir = await createTempRepository();
    await createSupportedRepository(rootDir);

    const result = await runInitCommand(
      {
        yes: false,
        performance: true,
        routes: [],
        externalSkillSet: "recommended",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: rootDir }
    );

    expect(result.exitCode).toBe(0);

    const perfArtifact = await readFile(path.join(rootDir, "agent-workflow", "artifacts", "PERF.md"), "utf8");
    const lighthouseConfig = await readFile(
      path.join(rootDir, "agent-workflow", "config", "lighthouserc.cjs"),
      "utf8"
    );
    const lighthouseScript = await readFile(path.join(rootDir, "scripts", "run-lighthouse.mjs"), "utf8");
    const performanceSkill = await readFile(
      path.join(rootDir, ".agents", "skills", "performance-lighthouse-audit", "SKILL.md"),
      "utf8"
    );

    expect(perfArtifact).toContain("# Audited Routes");
    expect(lighthouseConfig).toContain('"/dashboard"');
    expect(lighthouseScript).toContain("auditedRoutes");
    expect(performanceSkill).toContain("name: performance-lighthouse-audit");
  });

  it("selects external skills by preset and eligibility", async () => {
    const minimalRoot = await createTempRepository();
    await createSupportedRepository(minimalRoot);

    const minimalResult = await runInitCommand(
      {
        yes: false,
        performance: false,
        routes: [],
        externalSkillSet: "minimal",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: minimalRoot }
    );

    expect(minimalResult.exitCode).toBe(0);
    await expect(
      readFile(path.join(minimalRoot, ".agents", "skills", "web-design-guidelines", "SKILL.md"), "utf8")
    ).rejects.toThrow();

    const fullRoot = await createTempRepository();
    await createSupportedRepository(fullRoot);

    const fullResult = await runInitCommand(
      {
        yes: false,
        performance: true,
        routes: [],
        externalSkillSet: "full",
        overwriteManaged: false,
        dryRun: false,
        help: false
      },
      { cwd: fullRoot }
    );

    expect(fullResult.exitCode).toBe(0);

    const optionalSkill = await readFile(
      path.join(fullRoot, ".agents", "skills", "next-cache-components", "SKILL.md"),
      "utf8"
    );

    expect(optionalSkill).toContain("name: next-cache-components");
  });
});
