import { pathToFileURL } from "node:url";
import process from "node:process";

import { formatInitSummary, parseInitArgs, runInitCommand } from "./commands/init.js";
import { formatUpdateSummary, parseUpdateArgs, runUpdateCommand } from "./commands/update.js";
import { PACKAGE_VERSION } from "../package-version.js";

export interface CliIO {
  stdout: (message: string) => void;
  stderr: (message: string) => void;
}

export interface CliEnvironment {
  cwd: string;
}

const defaultIO: CliIO = {
  stdout: (message) => {
    process.stdout.write(`${message}\n`);
  },
  stderr: (message) => {
    process.stderr.write(`${message}\n`);
  }
};

function formatHelp(): string {
  return [
    "next-codex-workflow",
    "",
    "Usage:",
    "  next-codex-workflow init [options]",
    "  next-codex-workflow update [options]",
    "",
    "Global options:",
    "  --help                                    Show this help",
    "  --version                                 Show package version",
    "",
    "Init options:",
    "  --yes                                     Accept default choices automatically",
    "  --performance                             Generate Lighthouse performance workflow files",
    "  --routes <comma-separated-routes>         Routes to audit when performance mode is enabled",
    "  --external-skill-set <minimal|recommended|full>",
    "                                            Choose which bundled external skills to copy",
    "  --workflow-mode <single-agent|multi-agent>",
    "                                            Choose whether workflow shortcuts stay in one thread or spawn specialist agents",
    "  --overwrite-managed                       Replace files previously generated by this tool",
    "  --dry-run                                 Print planned changes without writing files",
    "  --help                                    Show this help",
    "",
    "Update options:",
    "  --yes                                     Accept default choices automatically",
    "  --dry-run                                 Print planned changes without writing files",
    "  --help                                    Show this help"
  ].join("\n");
}

export async function runCli(
  argv: string[],
  io: CliIO = defaultIO,
  environment: CliEnvironment = { cwd: process.cwd() }
): Promise<number> {
  const [command, ...commandArgs] = argv;

  if (!command || command === "--help" || command === "-h") {
    io.stdout(formatHelp());
    return 0;
  }

  if (command === "--version" || command === "-v") {
    io.stdout(PACKAGE_VERSION);
    return 0;
  }

  if (command === "update") {
    const parsed = parseUpdateArgs(commandArgs);

    if (!parsed.ok) {
      io.stderr(parsed.error);
      return 1;
    }

    if (parsed.options.help) {
      io.stdout(formatHelp());
      return 0;
    }

    const result = await runUpdateCommand(parsed.options, { cwd: environment.cwd });

    io.stdout(formatUpdateSummary(result));
    return result.exitCode;
  }

  if (command !== "init") {
    io.stderr(`Unknown command: ${command}`);
    io.stderr("");
    io.stderr(formatHelp());
    return 1;
  }

  const parsed = parseInitArgs(commandArgs);

  if (!parsed.ok) {
    io.stderr(parsed.error);
    return 1;
  }

  if (parsed.options.help) {
    io.stdout(formatHelp());
    return 0;
  }

  const result = await runInitCommand(parsed.options, { cwd: environment.cwd });

  io.stdout(formatInitSummary(result));
  return result.exitCode;
}

function isDirectExecution(): boolean {
  const entryPath = process.argv[1];

  if (!entryPath) {
    return false;
  }

  return import.meta.url === pathToFileURL(entryPath).href;
}

if (isDirectExecution()) {
  void runCli(process.argv.slice(2)).then((exitCode) => {
    process.exitCode = exitCode;
  });
}
