import type { InitOptions } from "../cli/commands/init.js";
import type { RepositoryInspection } from "../detect/inspect-repository.js";

export const MANAGED_FILE_MARKER = "Generated by next-codex-workflow-kit";

export interface GenerationContext {
  inspection: RepositoryInspection;
  options: InitOptions;
}

export interface GeneratedFile {
  relativePath: string;
  content: string;
}

export interface WriteAction {
  kind: "create" | "overwrite";
  relativePath: string;
}
